Added "useMoment". Dates can now also be timestams (millis). Not only
React9k/react-timeline-9000 pull request #241
Opened 2021-12-13 08:54 UTC by cristian-spiescu

Cf. #221

2022-01-29 09:13 UTC, lilfolr requested changes
I dont understand the `useMoment` prop?  
If I understand correctly, the idea behind this is to allow users to supply either a number or a moment as an item prop. So internally we could just convert it to a moment and the client is none the wiser?

2022-02-17 18:11 UTC, cristian-spiescu commented
> I dont understand the `useMoment` prop? If I understand correctly, the idea behind this is to allow users to supply either a number or a moment as an item prop. So internally we could just convert it to a moment and the client is none the wiser?

I'm not sure if you've read [this doc](https://github.com/flower-platform/react-timeline-9001/blob/not-using-moment-for-dates-squash/docs/date-types.md). If not, could you please take a look at it? It sheds some light on the "why" behind this feature + design decisions.

2022-02-17 18:16 UTC, cristian-spiescu commented on src/utils/timeUtils.js
> + * @returns moment
"useMoment = true", which is the default == the initial behavior where the user provided dates are in moment format. Hence NO transformation is needed.

"useMoment = false" => the user works ONLY w/ normal timestamps. So we need to convert them internally to moment, to be understood by the original code.

2022-02-17 18:16 UTC, cristian-spiescu commented on src/utils/timeUtils.js
> +export function convertDateToMoment(date, useMoment) {
Yes, cf. my previous remark.

2022-02-22 10:14 UTC, lilfolr commented on src/utils/itemUtils.test.js
> +  return convertDateToMoment(item.end, true);
I cant get this anymore - hopefully its fixed

2022-02-22 10:14 UTC, merged